### ISSUE TITLE
make check stucks

### ISSUE THREAD

**Issue by mmn980** [libbtc/libbtc#143]
Hello! On ubuntu 18 build seems to be completed successfully, however, after i execute make check the only output is:
make[1]: Entering directory '/home/user/githubs/libbtc'
make  check-TESTS
make[2]: Entering directory '/home/user/githubs/libbtc'
make[3]: Entering directory '/home/user/githubs/libbtc'

and then it freezes with blinking cursor, doesnt return to shell, nor shows any signs of life
(/home/user/githubs/libbtc is the folder to which i pulled the code)

**Comment by maxx-t** [comment]
Got the same issue under Archlinux, running `make check` with debug options it ends with : 

`$ LANG=en; make check -d`:
```
     Prerequisite 'libbtc.la' is older than target 'tests'.
    No need to remake target 'tests'.
   Finished prerequisites of target file 'tests.log'.
  Must remake target 'tests.log'.
Putting child 0x2506260 (tests.log) PID 1928 on the chain.
Live child 0x2506260 (tests.log) PID 1928
```

`$ LANG=en; make check --debug`:
```
Reading makefiles...
Updating makefiles....
Updating goal targets....
 File 'test-suite.log' does not exist.
   File 'tests.log' does not exist.
         Prerequisite 'src/stamp-h1' is newer than target 'src/libbtc-config.h'.
        Must remake target 'src/libbtc-config.h'.
make[3]: Entering directory '/home/max/Documents/FORKS/libbtc'
        Successfully remade target file 'src/libbtc-config.h'.
  Must remake target 'tests.log'.
```

**Comment by Andrade** [comment]
In Ubuntu 18.04 I got the same (or similar) problem, but it turns out it wasn't stuck. I left it alone for some time (can't really tell how long, maybe 15 minutes) and the test terminated (failed).

The test suite appears to include (real) network tests, which might help explain why it is slow.

```
make  check-TESTS
make[2]: Entering directory '/home/daniel/vc/libbtc'
make[3]: Entering directory '/home/daniel/vc/libbtc'
./build-aux/test-driver: line 107:   380 Bus error               (core dumped) "$@" > $log_file 2>&1
FAIL: tests
============================================================================
Testsuite summary for libbtc 0.1
============================================================================
# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See ./test-suite.log
Please report to https://github.com/jonasschnelli/libbtc/issues
============================================================================
Makefile:2011: recipe for target 'test-suite.log' failed
make[3]: *** [test-suite.log] Error 1
make[3]: Leaving directory '/home/daniel/vc/libbtc'
Makefile:2117: recipe for target 'check-TESTS' failed
make[2]: *** [check-TESTS] Error 2
make[2]: Leaving directory '/home/daniel/vc/libbtc'
Makefile:2348: recipe for target 'check-am' failed
make[1]: *** [check-am] Error 2
make[1]: Leaving directory '/home/daniel/vc/libbtc'
Makefile:1897: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1
```

The log file: [test-suite.log](https://github.com/libbtc/libbtc/files/3043093/test-suite.log)

**Comment by xloem** [comment]
The reason this appears to happen is probably because the test actually syncs the entire blockchain.  A message letting the user know about this would likely help.

Andrade's issue appears to be something else.  @Andrade if your test failure still occurs, could you open another issue for it?

`make check` is actually run on travis on multiple machines for every push to this repository.  It is indeed quite possible for those tests to complete successfully.

**Comment by xloem** [comment]
It looks like it would be good to change the tests eventually so that the entire chain is not synced, but for now I think #176 addresses this.

**Comment by xloem** [comment]
> ./build-aux/test-driver: line 107:   380 Bus error               (core dumped) "$@" > $log_file 2>&1

> The log file: [test-suite.log](https://github.com/libbtc/libbtc/files/3043093/test-suite.log)

This is #157 because SIGBUS is exit status 135.
